# Generated by Django 2.1.2 on 2018-10-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='edition',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='service',
            name='isbn',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='selleremail',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='sellername',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='sellerphone',
            field=models.CharField(max_length=200),
        ),
    ]
