# Generated by Django 2.1.2 on 2018-10-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20181015_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(default='isqa-0000', max_length=200),
        ),
    ]
